### ISSUE TITLE
Shiny app

### ISSUE THREAD

**Issue by bczernecki** [bczernecki/imgw#10]
Dla osóby nie-eRowych może warto dorzucić interfejs w shiny z outputem w formie XLS(X)/CSV?

- [ ] selection by location

**Comment by Nowosad** [comment]
Wewnatrz pakietu (e.g. jako rstudio addin) czy poza pakietem (e.g. jako strona www)?

**Comment by bczernecki** [comment]
Raczej to drugie - głównie na potrzeby artykułu
