### ISSUE TITLE
Dodac dokumentacje do danych

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/imgw#11]

**Comment by bczernecki** [comment]
Co masz na myśli?

**Comment by Nowosad** [comment]
to tylko dla mnie przypomnienie - dodać plik stacje_meteo.R tłumaczący co znajduje się w pliku stacje_meteo.rda (e.g. projekcja, etc.)

**Comment by Nowosad** [comment]
https://github.com/bczernecki/imgw/blob/master/R/stacje_meteo.R
