### ISSUE TITLE
hydro.R do poprawy

### ISSUE THREAD

**Issue by aglogowski** [bczernecki/imgw#12]
Dokończenie kodu dla dobowych i półrocznych danych.
Czy lepiej zrobić czy różne funkcje czy może, czy różne wyniki w zależności od interwału danych?

**Comment by aglogowski** [comment]
nie usuwa braków obserwacji

**Comment by Nowosad** [comment]
@aglogowski założenie jest takie, że najlepiej byłoby stworzyć trzy funkcje, np. `hydro_dobowe()`, `hydro_miesieczne()`, `hydro_roczne()`. Główna funkcja `hydro()` ma tylko wołać później jedną z tamtych.
