### ISSUE TITLE
dane_hydro

### ISSUE THREAD

**Issue by aglogowski** [bczernecki/imgw#13]
1. Czy istnieje taka baza stacji hydrologicznych jak "stacje_meteo" ? - dodanie coords.

2. W przypadku danych terminowych - czy używaliście kiedyś funkcji gc() nie do końca wiem, czy istnieją jakieś skutki uboczne ale ja używałem tego jak zwalniało mi czytanie plików(duże lub dużo plików). Dzięki gc() uwalnia RAM, który jest używany mimo, że jakiś plik został już dawno przeczytany?

3. Aktualnie hydro_roczne pobiera wybrany przez użytkownika format -> Stan H, Przepływ Q, Temperatura T, czy warto to przerobić tak, żeby pobierał wszystko ? Każda z tych danych różni się dokładnie jedną kolumną. 

4. opisy danych - 1- min, 2-srednia, 3-max -> można to umieścić w nazwie kolumny ? Dla mnie jest to najprostsza forma ale czy tak wypada?

**Comment by bczernecki** [comment]
Ad. 1. Powinno być wszystko razem. @Nowosad - możesz sprawdzić na jakimś przykładzie?
Ad. 2. garbage collector nie ma tutaj za bardzo sensu
Ad. 3. Czy te elementy są w jednych zipach? Jeśli tak to nie ma sensu tego rozdzielać? Jeśli jest to kwestia oddzielnych plików to trzeba napisac kod, który dla >1 elementu będzie na poziomie funkcji pobierać odpowiednio więcej danych i potem je łączyć mergem.
Ad. 4. Trzeba dodać argument dla funkcji pobierającej czy zmienić/uprościć nazwy kolumn. Opisać do tego w dokumentacji

**Comment by aglogowski** [comment]
Ad.3 są w 3 różnych zipach czyli trzeba rozbudować

Ad.4 Jeżeli już dodawać zmienną,która upraszcza nazwy kolumn to wtedy już do konwencji z wątku Funkcja skracająca nazwy kolumn #6 ?
