### ISSUE TITLE
README.Rmd

### ISSUE THREAD

**Issue by aglogowski** [bczernecki/imgw#15]
Wiem, że nie wszystkie funkcje będą dostępne dla użytkownika. Czy te funkcje meteo/hydro _ dobowe/miesięczne/roczne będą wchodziły w skład dokumentacji czy tylko te główne funkcje hydro i meteo ?

**Comment by Nowosad** [comment]
Też będą wchodziły.
`meteo()` - jest dobre dla doświadczonych użytkowników (albo osób, które chcą ściągnąć wszystko), natomiast `meteo_miesieczne()`, etc. jest mniej wymagające i od razu sugeruje co się pobiera - myślę, że będzie to częściej używane.

README na razie nie ma się co za bardzo przejmować - dokumentacja pewnie i tak będzie bardziej jako vignettes (+ strona pkgdown).
