### ISSUE TITLE
pobieranie przestalo dzialac

### ISSUE THREAD

**Issue by bczernecki** [bczernecki/imgw#18]
Świeża instalacji na Windowsie zwraca:

> a <- meteo_dobowe()
Error in read.table(file = FILE, header = header, sep = sep, row.names = row.names,  : 
  no lines available in input

**Comment by bczernecki** [comment]
@Nowosad - sprawdź proszę w sali komputerowej na losowym kompie działanie z install_github() ...
- podejrzewam że export pakietów na Windowsie przy instalowaniu zależności nie trybi...

**Comment by Nowosad** [comment]
Na moich czysto-Windowsowskich testach nie mogłem odtworzyć tego problemu.
