### ISSUE TITLE
Plany

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/imgw#2]
Plany:
- [x] - pobieranie danych meteorologicznych (dobowe, miesięczne, terminowe) z https://dane.imgw.pl/
- [x] - pobieranie danych hydrologicznych (dobowe, miesięczne, pólroczne/roczne)  z https://dane.imgw.pl/
- [x] - możliwość pobierania wybranego roku
- [x] - możliwość pobierania wybranej stacji
- [x] - usunięcie statutów pomiarów, które na stacjach wyższych rzędów bardziej zaśmiecają niż pomagają
- [x] - możliwość zamiany nazw zmiennych w kolumnach na skrótowe + wybór podstawowych elementów 
- [ ] - dodanie funkcji z historycznymi zakresami pomiarowych (lub uwzględnić przy danych przestrzennych w punkcie niżej)
- [x] - dodanie danych przestrzennych z lokalizacjami stacji
- [ ] - przechowywanie (wraz z możliwością pobrania) kopii danych w formacie R na innym repo
- [x] - stworzenie strony internetowej (pkgdown)
- [ ] - https://dane.imgw.pl/regulations

**Comment by bczernecki** [comment]
[scan.pdf](https://github.com/bczernecki/imgw/files/3022845/scan.pdf)

**Comment by Nowosad** [comment]
https://github.com/bczernecki/imgw/issues/8#issuecomment-480022121
