### ISSUE TITLE
Add hydro stations

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/imgw#24]

**Comment by Nowosad** [comment]
@bczernecki przejrzyj pliki meteo i hydro ze wspolrzednymi i pomyśl jakie potrzebujemy kolumny (np. w hydro nie ma wielu kodów stacji)

**Comment by aglogowski** [comment]
nie wiem czy to się przyda ale IMGW udostępnia listę stacji bez współrzędnych. Nie wiem jak wygląda plik hydro ale może jakiś merge się uda ? 
https://dane.imgw.pl/data/dane_pomiarowo_obserwacyjne/dane_hydrologiczne/lista_stacji_hydro.csv

**Comment by Nowosad** [comment]
Dzięki za info @aglogowski - jutro to zobaczę.

**Comment by aglogowski** [comment]
To chyba do zamknięcia wątek już ?
