### ISSUE TITLE
Type-stability for meteo_sounding()

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/imgw#28]
Jedna funkcja powinna zwracać jeden typ danych. Dlaczego `meteo_sounding()` powinno zwracać albo listę albo data frame? Jest tutaj jakiś powód?

**Comment by Nowosad** [comment]
\+ ogólnie bycie type-stable dla reszty funkcji.

**Comment by bczernecki** [comment]
Zwraca teraz za każdym razem listę. Pierwszy element to tabela z wartościami sondowania. Drugi element listy to indeksy termodynamiczne+metadane
