### ISSUE TITLE
Hydro metadata type

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/imgw#29]
Wszystkie metadane dotyczace meteo są listami (z jedną lub dwoma ramkami danych). 
W przypadku metadanych hydro, dzienne to lista z dwoma wektorami tekstowymi, miesięczne to wektor tekstowy, a roczne to ramka danych z trzema kolumnami (factors). 
Przydałaby się tutaj jakaś standaryzacja. Jakieś pomysły @bczernecki ? @aglogowski ?

**Comment by aglogowski** [comment]
Zamienić wszystkie metadane hydro na listy ? Wtedy meteo byłoby listami ramek danych a hydro listami wektorów o różnej długości ?

**Comment by Nowosad** [comment]
A może zamienić hydro na listy z ramkami danych z jedną kolumną?

**Comment by aglogowski** [comment]
Dobra to ja to zmienię w swoim kodzie jeżeli uznajemy to za standaryzację. Listy z jedno kolumnowymi ramkami danych dla hydro ok ?
