### ISSUE TITLE
meteo_miesieczne.R

### ISSUE THREAD

**Issue by bczernecki** [bczernecki/imgw#3]
TODO:

- [x] DODAC %>%  oraz data.table z rbindlist() do eksportowanych funkcji:
- [x] Dane miesieczne maja 2 rodzaje plikow; w tej chwili pobiera sie tylko pierwszy rodzaj danych; drugi jest ignorowany; Trzeba sprawdzić czy po pobraniu mają taką samą liczbę wierszy. Jeśli tak można je od razu złączyć po kolumnach i problem z perspektywy użytkownika jest rozwiązany
- [x] zamiast laczyc w rbind.data.frame lepiej w listy i pozniej poleciec rbindlistem -> bardziej efektywne, ale nie wiadomo czy nie nastreczy ewentualnych problemow czesci uzytkownikow
- [x] w tej chwili uzytkownik pobiera wszystkie lata; byc moze warto dac mu wybor - przyda sie takze w innych funkcjach pobierajacych

**Comment by Nowosad** [comment]
Inne pytania/komentarze:

1. Czy potrzebujemy `left_join()` - bazowy `merge()` nie wystarczy
2. Język - czy nazwy argumentów mają być po polsku czy angielsku (np. interval vs interwal)?

**Comment by bczernecki** [comment]
>     1. Czy potrzebujemy `left_join()` - bazowy `merge()` nie wystarczy
Raczej nie. Klasyczny merge powinien wystarczyć
>     2. Język - czy nazwy argumentów mają być po polsku czy angielsku (np. interval vs interwal)?
Przeniesione do dyskusji w https://github.com/bczernecki/imgw/issues/9
