### ISSUE TITLE
Świeża instalacja na Windows nie działa:

### ISSUE THREAD

**Issue by bczernecki** [bczernecki/imgw#30]
Po usunięciu katalogu i próbie przeinstalowania paczki w sali 10-12:

```
library(devtools)
install_github("bczernecki/imgw", ref = "master", force=T)

library(imgw)
imgw::meteo_monthly(rank="synop", year=2018)

Error in read.table(file = FILE, header = header, sep = sep, row.names = row.names,  : 
  no lines available in input
```

Na pierwszy rzut oka wydaje mi się że z tym może być problem:
```
clean_metadata_meteo
Error: object 'clean_metadata_meteo' not found
```

Nie widzę tego obiektu do eksportu w: NAMESPACE

**Comment by Nowosad** [comment]
@bczernecki `clean_metadata_meteo()` nie jest specjalnie eksportowana - to jest funkcja wewnętrzna. (Możesz ją zawołać `imgw:::clean_metadata_meteo()`).

Na 95% problemem jest tutaj to, że plik się nie pobrał. Zobacz to - https://stackoverflow.com/questions/13613270/how-to-fix-the-error-in-r-of-no-lines-available-in-input. Prawodpodobnie dobrą opcją byłoby dodanie jakiejś pętli while (z opóźnieniem) przy pobieraniu, a w przypadku braku danych po iluś iteracjach to error..

**Comment by bczernecki** [comment]
Problem znaleziony w clean_meteodata_meteo():
```
a <- suppressWarnings(na.omit(read.fwf(address, widths = c(1000),
                                         fileEncoding = "CP1250", stringsAsFactors = FALSE)))
```
Po usunieciu fragmentu odpowiedzialnego za kodowanie (fileEncoding = 'CP1250') - pobieranie w trybie debugowania dziala, aczkolwiek polskie znaki sie krzacza

**Comment by bczernecki** [comment]
Pobieranie z readLines + iconv działa na Windowsie i Linuxie. Może implikować jednak dalsze błędy wszędzie gdzie występują polskie znaki. Work in progress...

**Comment by bczernecki** [comment]
Usunieto polskie znaki poprzez konwersje do ASCII/TRANSLIT. 
Pobieranie na Windowsie zaczelo dzialac :)

**Comment by Nowosad** [comment]
A jaki był problem z `a <- iconv(a, from = "cp1250", to = 'UTF-8')`?

**Comment by bczernecki** [comment]
Angielski windows nie konwertował wszystkich znaków z cp1250
