### ISSUE TITLE
MacOS unzipping problem + matching by column names

### ISSUE THREAD

**Issue by bczernecki** [bczernecki/imgw#31]
Na jednym MacOSie instalacja przebiegła prawidłowo, ale błąd wystąpił przy meteo_daily() na etapie łączenia.

Na drugim MacOSie wysypało sie już przy instalacji (zrzut ekranu poniżej)
![Zrzut ekranu 2019-04-24 o 14 06 15](https://user-images.githubusercontent.com/8086055/56670040-666ad500-66b2-11e9-8930-b67ca691e0ca.png)

**Comment by Nowosad** [comment]
Czy na tym drugim możesz zainstalować jakikolwiek pakiet z githuba?

**Comment by bczernecki** [comment]
To był komp studentki, więc raczej błąd nie do powtórzenia w normalnych warunkach ;)

**Comment by bczernecki** [comment]
Bugs not related to our package but to external factors. Closing
