### ISSUE TITLE
"daily", "precip" error

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/imgw#32]
``` r
library(imgw)
x <- meteo("daily", "precip", year = 2018)
#> Error in meteo_daily(rank = rank, year = year, status = status, coords = coords, : object 'data2' not found
```

<sup>Created on 2019-04-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by bczernecki** [comment]
Dzięki za czujność. Powinno teraz działać. Thx.

**Comment by Nowosad** [comment]
coolcoolcool. Kwestie meteo zbliżają się do wersji beta.
