### ISSUE TITLE
Dodanie brakujących współrzędnych w bazie hydro

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/imgw#36]
|        id|station               |
|---------:|:---------------------|
| 149180010|KRZYŻANOWICE          |
| 151160130|ŚCINAWA               |
| 150170160|BRANICE               |
| 149180060|CIESZYN               |
| 149180050|ZEBRZYDOWICE          |
| 150180220|GLIWICE               |
| 150180160|PYSKOWICE-DZIERŻNO    |
| 150160170|BYSTRZYCA KŁODZKA     |
| 150160260|BOLESŁAWÓW            |
| 150189998|WIERZCHY              |
| 150160280|BORÓW                 |
| 151170070|ODOLANÓW              |
| 151170040|ŁĄKI                  |
| 151160030|RADZYŃ                |
| 150150130|BŁAŻKOWA              |
| 150150080|JELENIA GÓRA          |
| 151150140|DĄBROWA BOLESŁAWIECKA |
| 151150080|ŻAGAŃ                 |
| 150150010|MIRSK                 |
| 151150090|ŁOZY                  |
| 150140100|BOGATYNIA             |
| 152170010|ŚREM                  |
| 152150080|SANTOK                |
| 152140070|KOSTRZYN NAD ODRĄ     |
| 151189991|ZAWADY                |
| 152180160|KONIN-MORZYSŁAW       |
| 152170190|KOCHOWO               |
| 152179997|WĄGROWIEC             |
| 152150220|ZBĄSZYŃ               |
| 152159998|MIĘDZYRZECZ           |
| 152180170|POPOWO                |
| 152179990|MOGILNO               |
| 152170090|ŻNIN                  |
| 153160300|WIELIMIE              |
| 153169994|DOBRZYCA              |
| 153160290|KOMORZE               |
| 152150280|GOŚCIM ZHP            |
| 153159999|KLUKI                 |
| 153140200|MORZYCZYN             |
| 154169998|CYBULINO              |
| 154170040|KWISNO                |
| 154169994|BROCZYNA              |
| 149180200|WISŁA-CZARNE          |
| 149180240|GOCZAŁKOWICE          |
| 151210170|PUŁAWY                |
| 151210210|KRÓLEWSKI LAS         |
| 152210170|WARSZAWA-BULWARY      |
| 152200150|WYCHÓDŹC              |
| 153189994|MĄTOWSKI CYPEL        |
| 150199999|MIĘDZYRZECZE          |
| 150190180|JELEŃ                 |
| 150190100|NIWKA                 |
| 149199995|UJSOŁY                |
| 149190130|ŁĘKAWICA              |
| 149190210|SUCHA BESKIDZKA       |
| 149200040|KASINKA MAŁA          |
| 150200070|BISKUPICE             |
| 149200160|KROŚCIENKO            |
| 149200190|GOŁKOWICE             |
| 149200240|NOWY SĄCZ             |
| 149190360|LUDŹMIERZ             |
| 149200300|MUSZYNA               |
| 150200050|MICHAŁÓW              |
| 149210030|KLĘCZANY              |
| 150210140|BRZEŹNICA             |
| 149210110|KROSNO                |
| 150220150|SUŁÓW                 |
| 151220120|PARCZEW               |
| 151220060|BORKI                 |
| 151200090|NOWE MIASTO           |
| 151200120|BIAŁOBRZEGI           |
| 150190300|BONOWICE              |
| 151200060|WĄSOSZ-STARA WIEŚ     |
| 152219998|PIASECZNO 1           |
| 152220080|SURAŻ                 |
| 153220170|OSOWIEC               |
| 153239999|AUGUSTÓW              |
| 153230050|PRZEWIĘŹ              |
| 153220200|RAJGRÓD               |
| 153220050|EŁK                   |
| 153229998|ORZECHOWO             |
| 153219988|RUDA                  |
| 153209992|WIELBARK              |
| 152230200|ZABUŻE                |
| 152210150|POPOWO                |
| 151230080|OKUNINKA              |
| 152220090|MIANOWO               |
| 152210160|ZAWADY                |
| 152190150|LUCIEŃ                |
| 152190130|LUCIEŃ-OŚRODEK        |
| 152190140|ZWIERZYNIEC           |
| 153170060|SWORNEGACIE           |
| 154170190|BORUCINO              |
| 154180270|PRUSZCZ GDAŃSKI       |
| 154180260|PRUSZCZ GDAŃSKI       |
| 154219999|BIEDASZKI             |
| 154220040|GOŁDAP                |
| 154220110|GOŁDAP 2              |
| 154220080|WRÓBEL                |
| 149190240|JABŁONKA              |

**Comment by bczernecki** [comment]
Dla stacji hydro pozostaje tylko 
http://monitor.pogodynka.pl/#map/19.467,53.6593,7,true,false,0
aczkolwiek parsowanie tego chyba nie wchodzi w grę :/

**Comment by bczernecki** [comment]
Zajmę się tym

**Comment by bczernecki** [comment]
Jakby co to można porównać zawartość z aktualną bazą monitora IMGW:
json <- fromJSON("http://monitor.pogodynka.pl/api/map/?category=hydro")

**Comment by Nowosad** [comment]
Partially fixed - https://github.com/bczernecki/imgw/commit/27a11dd9b7ac248217d3a8bbcc8f4aea7b2edc76
