### ISSUE TITLE
col_names = "polish"

### ISSUE THREAD

**Issue by bczernecki** [bczernecki/imgw#40]
Bug w pobieraniu polskich nazw kolumn, np.:
df <-  meteo(interval = "daily", rank = "synop", year = 2017, col_names = "polish")

**Comment by Nowosad** [comment]
Problem jest z sortowaniem danych na końcu kodu - https://github.com/bczernecki/imgw/blob/3d1d5c7bae85cd01ac9ca34800d0c8b8bb63eb2c/R/meteo_monthly.R#L133.

**Comment by Nowosad** [comment]
Teraz powinno działać. Określanie kolejności było w linijce po skracaniu nazw - https://github.com/bczernecki/imgw/commit/9146d00dfbbf405c0ff03ee015d6526e7a0f0db6
