### ISSUE TITLE
hydro - bledne pobieranie

### ISSUE THREAD

**Issue by bczernecki** [bczernecki/imgw#41]
Ponizszy kod pobiera wlasciwie tylko dane dla grudnia z tego co widze:

```r
x <- hydro("daily", year = 2010:2011, value = "H", col_names = 'polish')
head(x)

x2 <- x %>% filter(grepl("Lebsko",`Nazwa rzeki/jeziora`))
head(x2)

plot(x2$`Stan wody [cm]`)
```

**Comment by aglogowski** [comment]
Błąd naprawiony przy pobieraniu dane się nadpisywały. Jeżeli chodzi natomiast o Lebsko to w tym roku nie ma pomiarów z Lebska.
