### ISSUE TITLE
Ogimet data -TO DO

### ISSUE THREAD

**Issue by aglogowski** [bczernecki/imgw#42]
- [x] Koordynaty wszystkich synoptycznych stacji WMO 

- [x]  Zamiana kolumn typu char na numeric (nieznana całkowita ilość elementów w tabeli)

- [x] ogimet_daily

**Comment by aglogowski** [comment]
znalazłem takie stacje 
http://old.wetterzentrale.de/klima/stnlst.html
ale może macie już jakieś gotowe ? 
Sam ogimet ma informacje o szerokości i długości i wysokości. 
Pytanie czy chcemy dodać taki spis stacji jak w przypadku meto_stations ? Czy lepiej zczytywać z ogimetu?

**Comment by bczernecki** [comment]
- zaczytywałbym koordynaty bezpośrednio z ogimetu jeśli nie wymaga to jakiś rocket-science workaroundów i miliona paczek; choćby z tego względu że mamy stacje które zmieniały swoje lokalizacje i przyjmowanie jednego rozwiązania na sztywno będzie błędne.

- jeśli chodzi o rozdzielczość czasową to interesują nas tylko dobówki i godzinówki. resztę zostawiamy

**Comment by bczernecki** [comment]
@aglogowski - godzinówki są zrobione, zostawiam ci dobówki do zrobienia analoga i wrappera o nazwie 'ogimet' na ogimet_daily i ogimet_hourly

**Comment by aglogowski** [comment]
@bczernecki  dodałem daily i widzę błąd który próbowałem rozwiązać ale nie mogę znaleźć błędu w kodzie więc go dałem w koment, bo coś namieszałem i nie wiem gdzie. 
generalnie to co napisałeś działa tylko pod warunkiem, że:

-w aktualnej tabeli (b) znajdzie się mniej kolumn niż w tabeli data_station.
Chodzi o to że na sto procent w całej bazie znajdzie się jeszcze jakieś oznaczenie kolumny której nie ujęliśmy w tabeli początkowej(albo kiedyś pojawią się kolumny których teraz nie ma). Wydaje mi się, że najprościej zrobić instrukcję warunkową i mergować (tak jak w skomentowanym kodzie *linia 56 - 69*).

**Comment by bczernecki** [comment]
Nie powinno. Wziąłem nazwy z pełnego synopa dla wartości godzinowych, więc zakładam że jest to już pełna lista elementów które sa kodowane w synopie. Jak będę mieć wolną chwilę to rzucę okiem.
