### ISSUE TITLE
Funkcja skracająca nazwy kolumn

### ISSUE THREAD

**Issue by bczernecki** [bczernecki/imgw#6]
Domyślnie zwracane są pełne nazwy kolumn (np. "Średnia miesięczna temperatura [°C]"). Warto dopisać funkcję która pozwoli na skrócenie i dodać ją jako argument dla ogólnej funkcji pobierającej

**Comment by bczernecki** [comment]
3 pomysły:
- tam gdzie są dane dla statutu można wyciągnąć (najcześciej) 4 literowy skrót odpowiadający skrótowej nazwie pola wg IMGW
- można zaczerpnąć ze standardu GRIB NOAA: https://www.nco.ncep.noaa.gov/pmb/docs/on388/table2.html
- lub z ECMWF: https://apps.ecmwf.int/codes/grib/param-db?filter=grib2

**Comment by Nowosad** [comment]
@bczernecki jest jeszcze mały problem z dwoma nazwami:

```
    Warning: found non-ASCII strings
    'Wska<c5><ba>nik lodu [L/W]' in object 'abbrev'
    'Wska<c5><ba>nik wentylacji [W/N]' in object 'abbrev'
```
Możesz to sprawdzić, np:

```r
hourly <- meteo_hourly(rank = "climate", year = 1984)
head(hourly)
```

**Comment by Nowosad** [comment]
@bczernecki Jeszcze dwie kwestie:
1.  trzeba dodać do tego obiektu dokumentację
2. czy ten obiekt powinien się nazywać `abbrev`? Nie lepiej żeby były dwa obiekty `meteo_abbrev` i `hydro_abbrev`?

**Comment by bczernecki** [comment]
@Nowosad  - wstępnie ogarnięte. Można rozpocząć testy i poprawki

**Comment by aglogowski** [comment]
Zmodyfikowałem funkcję żeby skracały funkcję, nie wiem tylko czy dobrze stworzyłem plik rda ale to szybko wyjdzie w praniu. `hydro_abbrev` działa dokładnie tak samo jak `meteo_abbrev` tylko ja mam dużo mniejszą objętość po wyczyszczeniu duplikatów wyszło 18 kolumn. To taki komentarz @Nowosad  o obiektach.

**Comment by Nowosad** [comment]
@aglogowski

- Nie łączy niektórych nazw skrótów, np. zobacz  `x <- hydro("semiannual_and_annual", year = y, value = "H")`
- Dodatkowo na pewno są jakieś literówki, e.g. "Mesurment".
- Ja bym unikał slashy w nazwach skrótowych kolumn (`riv/lake` - może lepiej `riv_or_lake`?)

**Comment by aglogowski** [comment]
Naprawione, za literówki przepraszam ale mam `dysmuzgie ` :D i ich nie widzę....

**Comment by Nowosad** [comment]
@aglogowski 
- Nie łączy niektórych nazw skrótów, np. zobacz `hydro("daily", year = 2017)`

**Comment by aglogowski** [comment]
a faktycznie zapomonialem ze istnieje jeszcze plik ze zjawiskami hydrologicznymi

**Comment by aglogowski** [comment]
naprawione

**Comment by Nowosad** [comment]
@aglogowski  `x <- hydro("semiannual_and_annual", year = 2017, value = "H")` - tutaj też nie łączy wszystkiego

@aglogowski uprościlem też wszystkie elementy funkcji odpowiedzialne za wybór stacji (https://github.com/bczernecki/imgw/commit/5fe4b81c624ee33869c3073c69045b4c044a8a73). W razie co to stary kod jest w branchu old-stations (https://github.com/bczernecki/imgw/tree/old-stations). Myślę, że Twój pomysł z mądrzejszym ściąganiem jest dobry, ale może lepiej go wprowadzić później jak już przetestujemy to co jest..

**Comment by aglogowski** [comment]
Naprawione, Windows mi robi czasem psikusa i dostawia białe znaki ..... ale teraz już działa
