### ISSUE TITLE
readLines warning

### ISSUE THREAD

**Issue by bczernecki** [bczernecki/imgw#7]
Funkcja readLines, która jest używana do pobierania metadanych zwraca informację o błędnym zakończeniu pliku:

> meta <- metadane(interwal = "miesieczne", rzad = rzad)
Warning messages:
1: In readLines(file, n = thisblock) :
  incomplete final line found on 'https://dane.imgw.pl/data/dane_pomiarowo_obserwacyjne/dane_meteorologiczne/miesieczne/synop/s_m_d_format.txt'
2: In clean_metadata("https://dane.imgw.pl/data/dane_pomiarowo_obserwacyjne/dane_meteorologiczne/miesieczne/synop/s_m_d_format.txt",  :
  NAs introduced by coercion
3: In readLines(file, n = thisblock) :
  incomplete final line found on 'https://dane.imgw.pl/data/dane_pomiarowo_obserwacyjne/dane_meteorologiczne/miesieczne/synop/s_m_t_format.txt'

**Comment by bczernecki** [comment]
Dodanie funkcji read.fwf2(), która to obchodzi

**Comment by Nowosad** [comment]
@bczernecki - to warning. Wystarczyłoby pewnie tylko `  a <- na.omit(suppressWarnings(read.fwf(adres, widths = c(1000), fileEncoding = "CP1250", stringsAsFactors = FALSE)))`

**Comment by bczernecki** [comment]
ok. bedzie faktycznie szybciej :)
