### ISSUE TITLE
Czwartkowa niedrobnica

### ISSUE THREAD

**Issue by Nowosad** [bczernecki/imgw#8]
- [x] Usunięcie statutów
- [x] Dodanie danych przestrzennych
- [x] Wybór roku 
- [ ] Wybór stacji ??

**Comment by bczernecki** [comment]
Problem: Dane SYNOP w zipach mają końcówkę 3-cyfrową (np. 1966_1970_100_s.zip) wg klucza WMO (dokładnie to jest stacja 12100); W wewnętrznym identyfikatorze stacji stosowane są nazwy SZS (kilkucyfrowe)...
Z drugiej strony tylko przy stacjach SYNOP można zmniejszyć liczbę pobieranych plików. Proponuję dorzucić do https://github.com/bczernecki/imgw/blob/imgw2/raw-data/meteo_stacje.csv 3 cyfrowe identyfikatory, które pozwolą na wybór pobieranych SYNOPów
